export enum EnumRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  DOCTOR = 'DOCTOR',
  REFERRAL_DOCTOR = 'REFERRAL_DOCTOR',
  PATIENT = 'PATIENT',
  LAB_CORDINATOR = 'LAB_CORDINATOR',
  LAB_TECHNICIAN = 'LAB_TECHNICIAN',
  RECEPTIONIST = 'RECEPTIONIST',
  MARKETER = 'MARKETER',
  TECHNICAL_COORDINATOR = 'TECHNICAL_COORDINATOR'
}
